# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dispatch.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64ispatch.proto\"\x1f\n\x0e\x41\x64\x64ressRequest\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x0c\x41\x64\x64ressReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2R\n\x0e\x44ispatchServer\x12@\n\x1c\x44ispatchServerAddressRequest\x12\x0f.AddressRequest\x1a\r.AddressReply\"\x00\x62\x06proto3'
)




_ADDRESSREQUEST = _descriptor.Descriptor(
  name='AddressRequest',
  full_name='AddressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='AddressRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_ADDRESSREPLY = _descriptor.Descriptor(
  name='AddressReply',
  full_name='AddressReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='AddressReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='AddressReply.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['AddressRequest'] = _ADDRESSREQUEST
DESCRIPTOR.message_types_by_name['AddressReply'] = _ADDRESSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressRequest = _reflection.GeneratedProtocolMessageType('AddressRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSREQUEST,
  '__module__' : 'dispatch_pb2'
  # @@protoc_insertion_point(class_scope:AddressRequest)
  })
_sym_db.RegisterMessage(AddressRequest)

AddressReply = _reflection.GeneratedProtocolMessageType('AddressReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSREPLY,
  '__module__' : 'dispatch_pb2'
  # @@protoc_insertion_point(class_scope:AddressReply)
  })
_sym_db.RegisterMessage(AddressReply)



_DISPATCHSERVER = _descriptor.ServiceDescriptor(
  name='DispatchServer',
  full_name='DispatchServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='DispatchServerAddressRequest',
    full_name='DispatchServer.DispatchServerAddressRequest',
    index=0,
    containing_service=None,
    input_type=_ADDRESSREQUEST,
    output_type=_ADDRESSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISPATCHSERVER)

DESCRIPTOR.services_by_name['DispatchServer'] = _DISPATCHSERVER

# @@protoc_insertion_point(module_scope)
